var EVENT = {
    CREATE_ROOM: "CREATE_ROOM",
    JOIN_ROOM: "JOIN_ROOM",
    LEAVE_ROOM: "LEAVE_ROOM",
    FIND_ROOM: "FIND_ROOM",
    ROOM_BROADCAST: "ROOM_BROADCAST",
    CREATE_ROOM_RESULT: "CREATE_ROOM_RESULT",
    JOIN_ROOM_RESULT: "JOIN_ROOM_RESULT",
    LEAVE_ROOM_RESULT: "LEAVE_ROOM_RESULT",
    FIND_ROOM_RESULT: "FIND_ROOM_RESULT",
    ROOM_BROADCAST_RESULT: "ROOM_BROADCAST_RESULT",
    PLAYER_JOIN: "PLAYER_JOIN",
    PLAYER_LEAVE: "PLAYER_LEAVE",
};

module.exports = EVENT;
